### PR TITLE
Add linux-altera_4.2 back per request from stefan

### PR DESCRIPTION
**Pull request by dwesterg**
i did test the build and it is working.

### CODE REVIEW

**Comment by kraj** [comment]
I would like to start branching. I will merge this and than branch jethro out. Then we can remove all old kernels from master.

**Comment by dwesterg** [comment]
thanks. i was going to ask about doing that.  makes sense.

**Comment by kraj** [comment]
done now.

**Comment by nopeppermint** [comment]
so master branch is used for Yocto 2.1 and Jethro Branch for Yocto 2.0 ?

Does someone take care about the rocketboard wiki here for example
http://rocketboards.org/foswiki/view/Documentation/YoctoDoraBuildWithMetaAltera
and the influences from changes in meta-alter ?

**Comment by dwesterg** [comment]
i will, yes.

**Pull request merged**
