### PR TITLE
Update linux-altera-lts_5.4.bb

### PR DESCRIPTION
**Pull request by DavidMartinPhios**
set source revision to latest

### CODE REVIEW

**Comment by dwesterg** [comment]
Moving to AUTOREV is not recommended.  The versions specified which are versions extensively tested.

**Comment by DavidMartinPhios** [comment]
Ok. In this case the version "1f2f1ded05f1c6a1349fd0ffb20042679cd50d5e" does no more exists. Is there a well tested version for 5.4.86?

**Comment by kraj** [comment]
can you try latest master ? 37365b1f19b754fb15ef880e5c4f64b33424c359 should already fix it

**Comment by DavidMartinPhios** [comment]
Could you merge this rev into master? It seem that this commit does not belong to the master branch

**Comment by kraj** [comment]
oh it was unmerged. My bad. done now.

**Pull request closed without merging**
