### PR TITLE
General update on u-boot and kernel recipes

### PR DESCRIPTION
**Pull request by rebeccasf**

### CODE REVIEW

**Comment by dwesterg** [comment]
We could, but then we would have to disable yocto's kernel version check.  There is a check that compares the kernel version and the recipe PR I believe.  I played with this before and opted to just add the extra files.

Dalon

**Comment by kraj** [comment]
> We could, but then we would have to disable yocto's kernel version check. There is a check that compares the kernel version and the recipe PR I believe. I played with this before and opted to just add the extra files.
> 
> Dalon

you would still do `PV .= ".<minor_ver>"` inside recipe which should make kernel version check happy

**Comment by rebeccasf** [comment]
No problem, I will update the pull request once i tested the new changes. Thanks.

**Comment by rebeccasf** [comment]
@kraj can you help to review the latest patch series in this pull request? Thanks a lot.

**Pull request merged**
