### PR TITLE
Update kernel recipes to include new 4.1 ltsi kernel

### PR DESCRIPTION
**Pull request by dwesterg**
These patches update the kernel recipes to include the newly release 4.1 ltsi kernel as well as make available recipes for the 4.2 and 4.3 kernels.  In addition to this, i removed the in recipe kmeta data and instead use KBUILD_DEFCONFIG to specify the in kernel source defconfig to be used by default.  This will allow other layers to add configurations to the kernel using cfgs and other kernel metadata without having to resort to including their own defconfig in recipe.

Thanks,
dalon

### CODE REVIEW

**Comment by kraj** [comment]
Can you squash, the revert commits and typo commit to its parent commit ?

**Comment by dwesterg** [comment]
will do.

**Comment by dwesterg** [comment]
I believe i made all the changes requested.  The 4.1 LTSI kernel is added prior to removal of the 3.10 ltsi kernels

**Comment by kraj** [comment]
Is this series on top of latest meta altera

**Comment by dwesterg** [comment]
I thought it was.  I can pull down kraj/meta-altera and apply the patches
to check

**Comment by kraj** [comment]
i am not able to merge it since it says it has conflicts. so you need to rebase this pull branch on top of latest master and send again

**Comment by dwesterg** [comment]
will do.

**Pull request closed without merging**
