### PR TITLE
Update kernel recipes V3

### PR DESCRIPTION
**Pull request by dwesterg**
Update kernel recipes to include new LTSI branches and 4.5 / 4.6 kernels and clean up FILESEXTRAPATH.

### CODE REVIEW

**Comment by gizero** [comment]
After pulling this changeset in, I see bitbake complaining as follows and trying to build from the wrong SRCREV:

```
WARNING: FILESEXTRAPATHS-variable, must always use _prepend (or _append)
type of assignment, and don't forget the colon.
Please assign it with the format of:
  FILESEXTRAPATHS_append := ":${THISDIR}/Your_Files_Path" or
  FILESEXTRAPATHS_prepend := "${THISDIR}/Your_Files_Path:"
in your bbappend file

Your incorrect assignment is:
/home/gizero/work/decos/repo-krogoth/poky/../meta-altera/recipes-kernel/linux/linux-altera-ltsi:

```

How about @kraj https://github.com/kraj/meta-altera/pull/27#commitcomment-17998072 to V2 of this PR? I don't see `.=` operator used in the final assignment.

**Comment by dwesterg** [comment]
i will try it out.  i konw i missed the "."

**Comment by kraj** [comment]
I missed it too in review. I think I sent you the detailed expression on using .= or =.

**Comment by dwesterg** [comment]
i cut and paste your comment, i think it missed the "."  no biggie.  fixed
now :)

**Pull request merged**
